name = "forum-backend"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "production"
# CORS_ORIGIN = "https://forum1.pages.dev"
CORS_ORIGIN = "https://forum.wwjpl.dpdns.org"
JWT_SECRET = "FXjC$5FK[Oo}wBy8O.{g]}w?sXxJK,mT.GCiI1N.U_*8^Qj.!8?^&Q@mYh5u?ASZ"

[[d1_databases]]
binding = "DB"
database_name = "forum-database"
database_id = "134219ce-af5b-44fe-91e7-629c6ba4e910"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



